version: '2'
services:

  #------------- proxy -----------------#
  # nginx:    
  #   entrypoint: './wait-for-it.sh gateway:3001 web:3000 -s -- /start.sh'
  #   environment:
  #       - DOMAIN_NAME=aksenchyk.com
  #       - GATEWAY_SERVER_HOST=gateway
  #       - GATEWAY_SERVER_PORT=3001
  #       - LETSENCRYPT_HOST=letsencrypt
  #       - LETSENCRYPT_PORT=80
  #       - WEBROOT_PATH=/etc/letsencrypt
  #       - WEB_SERVER_HOST=web
  #       - WEB_SERVER_PORT=3000
  #   image: 'aksenchyk/fm-nginx:latest'
  #   ports:
  #       - '80:80'
  #       - '443:443'
  #   restart: always
  #   volumes_from:
  #       - letsencrypt
  #   depends_on:
  #       - gateway
  #       - web 
  #       - letsencrypt 
  # letsencrypt:
  #   environment:
  #     - DOMAINS=aksenchyk.com www.aksenchyk.com
  #     - EMAIL=aksenchyk.v@gmail.com
  #   image: 'aksenchyk/fm-letsencrypt:latest'  
  #   volumes:
  #     - /var/lib/letsencrypt
  #     - /etc/letsencrypt

  #--------- gateway   -----------------#
  gateway:
    image: aksenchyk/fm-200loc:latest
    ports:
     - "3001:3001"     
    environment:        
     - HTTP_PORT=3001
     - MONGO_HOST=profile-db
     - REDIS_HOST=redis
     - DEBUG=gateway,plugins:*
    depends_on:
     - profile-db
     - redis
    entrypoint: ./wait-for-it.sh profile-db:27017 redis:6379 -s -- npm run dev  

  dashboard:
    entrypoint: './wait-for-it.sh redis:6379 -s -- npm start -- p 5601 --link gateway:3001'
    environment:
      - REDIS_HOST=redis
    image: 'aksenchyk/200loc-dashboard:latest'
    ports:
      - '5601:5601'  
  #------------------------------------#


  #------- databases ------------------#
  #------------------------------------#
  cars-db:    
    image: mongo
  #------------------------------------#
  profile-db:    
    image: mongo
  #-------gateway persistance----------# 
  redis:
    image: 'redis:latest'
  #------------------------------------#


  #-------- microservices  ------------#
  #------------------------------------#
  cars:    
    image: aksenchyk/fm-cars:latest      
    environment:        
     - HTTP_PORT=80   
    depends_on:
      - cars-db
      - etcd
      - rabbitmq    
    environment: 
      - DBSOURCE_HOST=cars-db
      - BROCKER_HOST=rabbitmq
      - ETCD_HOST=etcd    
    entrypoint: ./wait-for-it.sh cars-db:27017 etcd:4001 rabbitmq:5672 -s -- npm run dev
    restart: always  
  #------------------------------------#  
  profile:
    image: aksenchyk/fm-profile:latest
    environment:        
     - HTTP_PORT=80    
    depends_on:      
      - etcd
      - rabbitmq
      - profile-db
    environment: 
      - DBSOURCE_HOST=profile-db
      - ETCD_HOST=etcd
      - BROCKER_HOST=rabbitmq
    entrypoint: ./wait-for-it.sh profile-db:27017 etcd:4001 rabbitmq:5672 -s -- npm run dev    
    restart: always
  #------------------------------------#
  tracker:    
    image: aksenchyk/fm-tracker:latest
    environment:        
     - HTTP_PORT=80      
    depends_on:      
      - etcd
      - rabbitmq     
    environment:      
      - ETCD_HOST=etcd
      - BROCKER_HOST=rabbitmq
    entrypoint: ./wait-for-it.sh etcd:4001 rabbitmq:5672 -s -- npm run dev
    restart: always
  #------------------------------------# 
  image:    
    image: aksenchyk/fm-image:latest
    environment:        
     - HTTP_PORT=80        
    depends_on:      
      - etcd
      - rabbitmq      
    environment:     
      - ETCD_HOST=etcd
      - BROCKER_HOST=rabbitmq
    entrypoint: ./wait-for-it.sh etcd:4001 rabbitmq:5672 -s -- npm run dev     
    restart: always    
  #------------------------------------#


  #-------- web client ----------------#
  web:
    image: aksenchyk/fm-web:latest  
    depends_on:      
      - etcd
    environment:
      - ETCD_HOST=etcd
      - HTTP_PORT=3000 
    entrypoint: ./wait-for-it.sh etcd:4001 -s -- npm start
    restart: always  
  #------------------------------------#



  #------- logical group  -------------#
  #------------------------------------# 
  etcd:
    command: '--name etcd -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -advertise-client-urls http://127.0.0.1:2379,http://127.0.0.1:4001'
    image: 'quay.io/coreos/etcd:v2.3.7'
    ports:
     - '2379:2379'
     - '4001:4001'
   
  #------------------------------------# 
  rabbitmq:    
    build: ./broker
    ports:
     - '5672:5672'
     - '15672:15672'
     - '1883:1883'
  #------------------------------------#
